In [1]:
import pandas as pd

In [2]:
data = pd.read_csv("/content/breast_cancer.csv")
data.head()

id diagnosis  ...  fractal_dimension_worst  Unnamed: 32
0    842302         M  ...                  0.11890          NaN
1    842517         M  ...                  0.08902          NaN
2  84300903         M  ...                  0.08758          NaN
3  84348301         M  ...                  0.17300          NaN
4  84358402         M  ...                  0.07678          NaN

[5 rows x 33 columns]

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 33 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   id                       569 non-null    int64  
 1   diagnosis                569 non-null    object 
 2   radius_mean              569 non-null    float64
 3   texture_mean             569 non-null    float64
 4   perimeter_mean           569 non-null    float64
 5   area_mean                569 non-null    float64
 6   smoothness_mean          569 non-null    float64
 7   compactness_mean         569 non-null    float64
 8   concavity_mean           569 non-null    float64
 9   concave points_mean      569 non-null    float64
 10  symmetry_mean            569 non-null    float64
 11  fractal_dimension_mean   569 non-null    float64
 12  radius_se                569 non-null    float64
 13  texture_se               569 non-null    float64
 14  perimeter_se             5

In [4]:
# If we look at this data set what is a problem in this
# 1. In diagnosis datatype is object when ever we apply ML or DL there should be no data is
#    in alphabatical format or in string format it should be in numeric format
# So we will convert it into numeric form
# we will convert M to 1 and B to 0
# because M = positive
# And B = Negetive

In [5]:
data.isnull().sum()

id                           0
diagnosis                    0
radius_mean                  0
texture_mean                 0
perimeter_mean               0
area_mean                    0
smoothness_mean              0
compactness_mean             0
concavity_mean               0
concave points_mean          0
symmetry_mean                0
fractal_dimension_mean       0
radius_se                    0
texture_se                   0
perimeter_se                 0
area_se                      0
smoothness_se                0
compactness_se               0
concavity_se                 0
concave points_se            0
symmetry_se                  0
fractal_dimension_se         0
radius_worst                 0
texture_worst                0
perimeter_worst              0
area_worst                   0
smoothness_worst             0
compactness_worst            0
concavity_worst              0
concave points_worst         0
symmetry_worst               0
fractal_dimension_worst      0
Unnamed:

In [6]:
# we will drop last column
data.columns

Index(['id', 'diagnosis', 'radius_mean', 'texture_mean', 'perimeter_mean',
       'area_mean', 'smoothness_mean', 'compactness_mean', 'concavity_mean',
       'concave points_mean', 'symmetry_mean', 'fractal_dimension_mean',
       'radius_se', 'texture_se', 'perimeter_se', 'area_se', 'smoothness_se',
       'compactness_se', 'concavity_se', 'concave points_se', 'symmetry_se',
       'fractal_dimension_se', 'radius_worst', 'texture_worst',
       'perimeter_worst', 'area_worst', 'smoothness_worst',
       'compactness_worst', 'concavity_worst', 'concave points_worst',
       'symmetry_worst', 'fractal_dimension_worst', 'Unnamed: 32'],
      dtype='object')

In [9]:
data.drop(["Unnamed: 32"], axis = 1, inplace = True)

In [11]:
data.drop(["id"], axis = 1, inplace = True)

In [12]:
data.isnull().sum()

diagnosis                  0
radius_mean                0
texture_mean               0
perimeter_mean             0
area_mean                  0
smoothness_mean            0
compactness_mean           0
concavity_mean             0
concave points_mean        0
symmetry_mean              0
fractal_dimension_mean     0
radius_se                  0
texture_se                 0
perimeter_se               0
area_se                    0
smoothness_se              0
compactness_se             0
concavity_se               0
concave points_se          0
symmetry_se                0
fractal_dimension_se       0
radius_worst               0
texture_worst              0
perimeter_worst            0
area_worst                 0
smoothness_worst           0
compactness_worst          0
concavity_worst            0
concave points_worst       0
symmetry_worst             0
fractal_dimension_worst    0
dtype: int64

In [17]:
# we will convert the value of diagnosis to 0 and 1
# here sklearn is scikit learn it is use for ML
from sklearn.preprocessing import  LabelEncoder # library for encoding
le = LabelEncoder()  # created the object
data['diagnosis'] = le.fit_transform(data['diagnosis'])
# Using map function
# data['diagnosis'] = data['diagnosis'].map({"B" = 0, "M" = 1})

In [18]:
data.head()

diagnosis  radius_mean  ...  symmetry_worst  fractal_dimension_worst
0          1        17.99  ...          0.4601                  0.11890
1          1        20.57  ...          0.2750                  0.08902
2          1        19.69  ...          0.3613                  0.08758
3          1        11.42  ...          0.6638                  0.17300
4          1        20.29  ...          0.2364                  0.07678

[5 rows x 31 columns]

In [19]:
# Now we are going to divide the data into features and target
# diagnosis is target and others are features
x = data.iloc[:,1:] # to take all the column except diagnosis -> first one is row and second on is column
y = data.iloc[:,0] 

In [20]:
x

radius_mean  texture_mean  ...  symmetry_worst  fractal_dimension_worst
0          17.99         10.38  ...          0.4601                  0.11890
1          20.57         17.77  ...          0.2750                  0.08902
2          19.69         21.25  ...          0.3613                  0.08758
3          11.42         20.38  ...          0.6638                  0.17300
4          20.29         14.34  ...          0.2364                  0.07678
..           ...           ...  ...             ...                      ...
564        21.56         22.39  ...          0.2060                  0.07115
565        20.13         28.25  ...          0.2572                  0.06637
566        16.60         28.08  ...          0.2218                  0.07820
567        20.60         29.33  ...          0.4087                  0.12400
568         7.76         24.54  ...          0.2871                  0.07039

[569 rows x 30 columns]

In [21]:
y

0      1
1      1
2      1
3      1
4      1
      ..
564    1
565    1
566    1
567    1
568    0
Name: diagnosis, Length: 569, dtype: int64

In [22]:
y.value_counts()

0    357
1    212
Name: diagnosis, dtype: int64

In [28]:
# now we will devide the data
# we have to devide it randomly because we can not take it in squence
from sklearn.model_selection import train_test_split  # train_test_split will take rows randomly
# if we devide x and y there will be 4 variable
xtrain, xtest, ytrain, ytest = train_test_split(x, y, train_size = 0.80, random_state = 1)

In [29]:
ytrain.value_counts()

0    285
1    170
Name: diagnosis, dtype: int64

In [30]:
len(ytrain)

455

In [34]:
# Neural Network
# for this we will use library Tensorflow/keras

In [32]:
import tensorflow.keras as tf

In [36]:
# Now we will create the blank model of neural network
model = tf.models.Sequential()  # Sequential is model of neural network this will creates blank model
# we can add any number of layer that we want to add
# Add the layer
model.add(tf.layers.Dense(16, input_dim = 30, activation = 'relu')) # 16 is no. of layer in hidden layer
                                            # input_dim is no. of neurons in input layer 
model.add(tf.layers.Dense(32, activation = 'relu'))  # next hidden layer
model.add(tf.layers.Dense(1, activation = 'sigmoid')) # Output layer   

# Compile the model
model.compile(loss = 'binary_crossentropy', optimizer = 'adam', metrics = ["accuracy"]) # optimizer -> gradent desend optimizer and adam is function which will add that



In [38]:
# Train the model
model.fit(xtrain, ytrain, epochs = 500)  # epochs is number of iteration

Epoch 1/500
15/15 [==============================] - 0s 2ms/step - loss: 0.1146 - accuracy: 0.9604
Epoch 2/500
15/15 [==============================] - 0s 2ms/step - loss: 0.1135 - accuracy: 0.9473
Epoch 3/500
15/15 [==============================] - 0s 2ms/step - loss: 0.1607 - accuracy: 0.9451
Epoch 4/500
15/15 [==============================] - 0s 1ms/step - loss: 0.0968 - accuracy: 0.9604
Epoch 5/500
15/15 [==============================] - 0s 2ms/step - loss: 0.0908 - accuracy: 0.9626
Epoch 6/500
15/15 [==============================] - 0s 2ms/step - loss: 0.0889 - accuracy: 0.9604
Epoch 7/500
15/15 [==============================] - 0s 2ms/step - loss: 0.0851 - accuracy: 0.9538
Epoch 8/500
15/15 [==============================] - 0s 2ms/step - loss: 0.1020 - accuracy: 0.9560
Epoch 9/500
15/15 [==============================] - 0s 2ms/step - loss: 0.1009 - accuracy: 0.9604
Epoch 10/500
15/15 [==============================] - 0s 2ms/step - loss: 0.1522 - accuracy: 0.9341
Epoch 11/

In [42]:
# Test the Model  or we have to do predictions from the testing data
ypred = model.predict(xtest)  # This output is exponential value
ypred = ypred.round()
ypred

array([[0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],

In [43]:
# to print actuel value
ytest

421    0
47     1
292    0
186    1
414    1
      ..
172    1
3      1
68     0
448    0
442    0
Name: diagnosis, Length: 114, dtype: int64

In [44]:
# to compare this 2
model.evaluate(xtest, ytest)

4/4 [==============================] - 0s 3ms/step - loss: 0.1491 - accuracy: 0.9386


[0.14910240471363068, 0.9385964870452881]

In [45]:
# Confusion Matrix 
# by this we will able to know how many sample of 0 are wrongly predicted or correctly predicted
# Same of 1 also
# this will always a squre matrix
# size of matrix = no. of class (in this case 2X2)


In [49]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(ytest, ypred)
cm

array([[71,  1],
       [ 6, 36]])

In [50]:
len(xtest)

114

In [51]:
type(ypred)

numpy.ndarray

In [53]:
# want to know where the sample is predicted wrong
#just have to compare the value and take the index of it
id = []
for i in range(len(ytest)):
  if ytest.iloc[i] != ypred[i]:
    id.append(i)

In [54]:
id

[4, 38, 72, 76, 77, 86, 111]

In [55]:
xtest.iloc[id]

radius_mean  texture_mean  ...  symmetry_worst  fractal_dimension_worst
414       15.130         29.81  ...          0.3233                  0.06165
41        10.950         21.35  ...          0.2964                  0.09606
40        13.440         21.58  ...          0.2994                  0.07146
38        14.990         25.20  ...          0.1565                  0.05504
135       12.770         22.47  ...          0.2829                  0.08067
501       13.820         24.49  ...          0.3651                  0.11830
68         9.029         17.33  ...          0.4228                  0.11750

[7 rows x 30 columns]

In [57]:
# we can take manual data to check prediction
model.predict([[12,13,45,67,89,23,45,78,98,76,12,13,45,67,89,23,45,78,98,76,12,13,45,67,89,23,45,78,98,76]])

array([[1.]], dtype=float32)