In [ ]:
import numpy as np

In [ ]:
#simpal Array[2D Array]

In [ ]:
a1 = np.array([[4,5,7],[2,3,4],[1,9,6]])
a1

array([[4, 5, 7],
       [2, 3, 4],
       [1, 9, 6]])

In [ ]:
a1.shape

(3, 3)

In [ ]:
a1.ndim #gives you dimention

2

In [ ]:
a1.dtype #type of data

dtype('int64')

In [ ]:
a1.max()

9

In [ ]:
a1.min()

1

In [ ]:
a1

array([[4, 5, 7],
       [2, 3, 4],
       [1, 9, 6]])

In [ ]:
a1.argmax() #location of max num

7

In [ ]:
a1.argmin() #location of min num

6

In [ ]:
a1.sum() #sum of all the elements

41

In [ ]:
a1.sum(axis =0) #column wise addition

array([ 7, 17, 17])

In [ ]:
a1.sum(axis = 1) #row wise addition

array([16,  9, 16])

In [ ]:
# picking any element from array (slicing of array)

In [ ]:
a1[2]

array([1, 9, 6])

In [ ]:
a1[:] 

array([[4, 5, 7],
       [2, 3, 4],
       [1, 9, 6]])

In [ ]:
a1[2:3] #index num 1 to index 2 

array([[1, 9, 6]])

In [ ]:
a1[:3]

array([[4, 5, 7],
       [2, 3, 4],
       [1, 9, 6]])

In [ ]:
a1[1]

array([2, 3, 4])

In [ ]:
a1[1][1]

3

In [ ]:
a1[1:4,1:3]

array([[3, 4],
       [9, 6]])

In [ ]:
# linspace function
# used to generate equidistant number
# here we don't have infinite range 
#  here we can fix the range whatever we want to take

In [ ]:
a2 = np.linspace(1,100,30) #first 2 is range and third one is number of sample I want
a2

array([  1.        ,   4.4137931 ,   7.82758621,  11.24137931,
        14.65517241,  18.06896552,  21.48275862,  24.89655172,
        28.31034483,  31.72413793,  35.13793103,  38.55172414,
        41.96551724,  45.37931034,  48.79310345,  52.20689655,
        55.62068966,  59.03448276,  62.44827586,  65.86206897,
        69.27586207,  72.68965517,  76.10344828,  79.51724138,
        82.93103448,  86.34482759,  89.75862069,  93.17241379,
        96.5862069 , 100.        ])

In [ ]:
a2 = np.linspace(1,100,10)
a2

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [ ]:
a2 = np.linspace(1,100,30)
a2 = a2.astype('int')
a2

array([  1,   4,   7,  11,  14,  18,  21,  24,  28,  31,  35,  38,  41,
        45,  48,  52,  55,  59,  62,  65,  69,  72,  76,  79,  82,  86,
        89,  93,  96, 100])

In [ ]:
# Arange Function 
# I can define the distance of the samples
a3 = np.arange(1,100,5) # first 2 is range and 3rd one is distance between 2 num 
a3

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81,
       86, 91, 96])

In [ ]:
len(a3) #count of data

20

In [ ]:
# Rendom Number
np.random.randint(100)  #any random number between  1 to 99


67

In [ ]:
# to fix this random number once it is generated 
np.random.seed(1) # this is kind of memory
np.random.randint(100)

37

In [ ]:
# want to get more than 1 num 
np.random.randint(10,100,20) #3rd is num of elements

array([78, 97, 97, 96, 23, 19, 17, 73, 71, 32, 67, 11, 10, 70, 91, 18, 98,
       23, 57, 82])

In [ ]:
np.random.randint(10,100,(4,5)) #want to get in array #random array

array([[35, 97, 17, 36, 35],
       [32, 19, 77, 33, 37],
       [47, 67, 93, 48, 18],
       [42, 44, 20, 33, 25]])