In [ ]:
# Here we are going to create 2 layers input and output from scratch
import numpy as np

In [ ]:
inputs = np.array([[0,0,1], [1,0,1], [1,1,0],[0,1,0]])
inputs

array([[0, 0, 1],
       [1, 0, 1],
       [1, 1, 0],
       [0, 1, 0]])

In [ ]:
outputs = np.array([[0], [1], [1],[0]])
outputs

array([[0],
       [1],
       [1],
       [0]])

In [ ]:
np.random.seed(10)
weights = np.random.random((3,1))  #second random will print values between 0 to 1 
                                  # if we write randint it will generate integer value
weights

array([[0.77132064],
       [0.02075195],
       [0.63364823]])

In [ ]:
sum = np.dot(inputs, weights) + 0.02 #0.02 is bias value
sum

array([[0.65364823],
       [1.42496888],
       [0.81207259],
       [0.04075195]])

In [ ]:
# We have to create Activation function
def activation(x):
  return 1/(1+np.exp(-x))
  

In [ ]:
pred_output = activation(sum)
pred_output

array([[0.65783211],
       [0.8061162 ],
       [0.69255099],
       [0.51018658]])

In [ ]:
pred_output.round() # This output is wrong
                  # we are expecting this output [[0], [1], [1],[0]] so we are 50% wrong
                  

array([[1.],
       [1.],
       [1.],
       [1.]])

In [ ]:
# Now we will calculate the error
sum = np.dot(inputs,weights) + 0.02
pred_output = activation(sum)
error = outputs - pred_output  #this is error in our case which should be 0
error

array([[-0.65783211],
       [ 0.1938838 ],
       [ 0.30744901],
       [-0.51018658]])

In [ ]:
# For reduce the error we will use Gradient descent and back propogation
def gradient(x,a):
  return a * x * (1-x)  # This is deravtive of sigmoid

In [ ]:
sum = np.dot(inputs,weights) + 0.02
pred_output = activation(sum)
error = outputs - pred_output  # This is error in our case which should be 0
change_in_wt = gradient(pred_output, error)  # Here I am passing error value as my learning rate
weights = weights + np.dot(inputs.T, change_in_wt) # This is back propogation
error  # Every time we run the code error will reduce

array([[-0.57640216],
       [ 0.20384117],
       [ 0.28624393],
       [-0.46487306]])

In [ ]:
inputs.T.shape # Here T is transpose

(3, 4)

In [ ]:
change_in_wt.shape

(4, 1)

In [ ]:
# if we want to get null value of error
# We can do training of network
for i in range(500):
  sum = np.dot(inputs,weights) + 0.02
  pred_output = activation(sum)
  error = outputs - pred_output  # This is error in our case which should be 0
  change_in_wt = gradient(pred_output, error)  # Here I am passing error value as my learning rate
  weights = weights + np.dot(inputs.T, change_in_wt) # This is back propogation
  # Every time we run the code error will reduce

In [ ]:
error

array([[-0.0487281 ],
       [ 0.03407751],
       [ 0.03407758],
       [-0.048728  ]])

In [ ]:
pred_output

array([[0.0487281 ],
       [0.96592249],
       [0.96592242],
       [0.048728  ]])

In [ ]:
pred_output.round() # Desired output

array([[0.],
       [1.],
       [1.],
       [0.]])